name: Render my document
on: push
jobs:
  render:
    name: Render my document
    runs-on: ubuntu-latest
    steps:
        - name: Set up Git repository
          uses: actions/checkout@v2

        - name: Check repository
          uses: actions/checkout@v3

        - uses: r-lib/actions/setup-pandoc@v2

        - uses: r-lib/actions/setup-r@v2

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: posterdown, pagedown, rmarkdown

        - name: Render Rmarkdown files
          run: |
            Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' poster.Rmd

        - name: Commit changes
          run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit -a -m 'Add changes' || echo "No changes to commit"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            force_with_lease: true
